(ns clojure-automation-starter.clojure-app-tests.clojure-test
  (:require [clojure.test :refer :all])
  (:use [etaoin.api :all ()])
  (:use [clojure-automation-starter.config.url_config :all ()])
  (:use [clojure-automation-starter.pages.clojure-app.clojure-book-page :all ()])
  (:use [clojure-automation-starter.pages.clojure-app.clojure-get-started-page :all ()])
  (:use [clojure-automation-starter.pages.clojure_app.clojure_home_page :all ()]))

(def driver (chrome))

;(doto driver
;  (go clojure-url)
;  (click-getting-started-btn)
;  (click-learn-clojure-link)
;  (back)
;  (click-resources-link)
;  (back)
;  (click-books-link)
;  ;(has-text? "Getting Started")
;  (quit))

(doto driver
  (go clojure-url)
  (click-overview)
  (back)
  (click-releases)
  (back)
  (click-api)
  (back)
  (click-reference)
  (back)
  (click-releases)
  (back)
  (click-guides)
  (back)
  (click-community)
  (back)
  (click-dev)
  (back)
  (click-search)
  (quit))